#!/usr/bin/env bash

echo "Operating SYStem CLI"

SCRIPT_DIR=${BASH_SOURCE%/*}
OSYS_WORKING_DIR="$HOME/.osys"
OSYS_OS_LIST="$OSYS_WORKING_DIR/os.list"
OSYS_TEMPLATE_DIR="$SCRIPT_DIR/src/templates"
SCRIPT_NAME="osys"

function init(){
  if [ ! -d "$OSYS_WORKING_DIR" ]; then
    echo "OSYS appears to be running for the first time..."

    mkdir "$OSYS_WORKING_DIR"
    touch "$OSYS_OS_LIST"
  fi
}

init

case "$1" in
    list)
        case "$2" in
          update)
              echo "Updating CentOS"
              CENTOS_VERSION="7.5.1804"
              CENTOS_MIRROR="http://sjc.edge.kernel.org/centos/$CENTOS_VERSION/isos/x86_64"
              HTML_ANCHORS_LIST="$(curl -sL $CENTOS_MIRROR | xmllint --html --xpath //a -)"
              DELIMITER="</a>"

              cp $OSYS_TEMPLATE_DIR/centos_template.json $OSYS_OS_LIST
              sed "s/CENTOS_VERSION/$CENTOS_VERSION/g" $OSYS_OS_LIST > $OSYS_OS_LIST.bak
              mv $OSYS_OS_LIST.bak $OSYS_OS_LIST

              ## START DEBUG BLOCK ##
              if [ ! -z "$DEBUG" ]; then
                echo "CENTOS_VERSION=$CENTOS_VERSION"
                echo "CENTOS_MIRROR=http://sjc.edge.kernel.org/centos/$CENTOS_VERSION/isos/x86_64"
                echo ""
                echo "Printing out HTML Anchors from centOS Mirror"
                echo "$(curl -sL $CENTOS_MIRROR | xmllint --html --xpath //a -)"
                echo ""
                echo "Copying centos_template.json to:"
                echo "cp $OSYS_TEMPLATE_DIR/centos_template.json $OSYS_OS_LIST"
              fi 
              ## END DEBUG BLOCK ##

              s=$HTML_ANCHORS_LIST$DELIMITER
              while [[ $s ]]; do
                CURRENT_ANCHOR=$(echo "${s%%"$DELIMITER"*}" | cut -d'>' -f2)
                if $(echo $CURRENT_ANCHOR | grep -Eiq "^centos.*iso$|^sha.*txt$"); then

                  ## START DEBUG BLOCK ##
                  if [ ! -z "$DEBUG" ]; then
                    echo "CURRENT ANCHOR Matching .iso || .sha: $CURRENT_ANCHOR"
                  fi
                  ## END DEBUG BLOCK ##

                  echo "Adding link"
                  FILETYPE=$(echo $CURRENT_ANCHOR | cut -d'-' -f4 | tr '[:upper:]' '[:lower:]')

                  if $(echo $FILETYPE | grep -Eiq "^[^sha]"); then
                    ISOTYPE_URL="${FILETYPE}_url"
                    sed "s@$ISOTYPE_URL@$CENTOS_MIRROR/$CURRENT_ANCHOR@g" $OSYS_OS_LIST > $OSYS_OS_LIST.bak
                    mv $OSYS_OS_LIST.bak $OSYS_OS_LIST
                  else
                    SHA_LIST="$(curl -sL $CENTOS_MIRROR/$FILETYPE)"
                    echo $SHA_LIST
                    echo "Printing SHA"
                  fi


                fi
                s=${s#*"$DELIMITER"};
              done;
            ;;
          *)
              ## START DEBUG BLOCK ##
              if [ ! -z "$DEBUG" ]; then
                echo "Dumping contents of OS List located at: $OSYS_OS_LIST"
              fi
              ## END DEBUG BLOCK ##

              cat "$OSYS_OS_LIST"
              echo ""
              echo "To update this list run ./osys list update"
            ;;
        esac
      ;;
    --help|-h)
        echo "Operating SYStem Manager is a tool for the download and management of various Linux distros"
        echo ""
        echo "You may want to start with seeing which Linux Distros and versions OSYS is currently aware of."
        echo "> ${SCRIPT_NAME} list"
        echo ""
        echo "Get more information running with DEBUG=on"
        echo "> DEBUG=on ${SCRIPT_NAME} list"
      ;;
    *)
        echo "Usage Instructions:"
        echo "> ./${SCRIPT_NAME} --help"
      ;;
esac

exit 0;
